//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borz.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Borz.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Compile_Desc_JustLog {
            get {
                return ResourceManager.GetString("Compile.Desc.JustLog", resourceCulture);
            }
        }
        
        internal static string Compile_Desc_Platform {
            get {
                return ResourceManager.GetString("Compile.Desc.Platform", resourceCulture);
            }
        }
        
        internal static string Generate_Desc_Watch {
            get {
                return ResourceManager.GetString("Generate.Desc.Watch", resourceCulture);
            }
        }
        
        internal static string Generate_Error_UnknownGenerator {
            get {
                return ResourceManager.GetString("Generate.Error.UnknownGenerator", resourceCulture);
            }
        }
        
        internal static string Generate_ListAvailableHeader {
            get {
                return ResourceManager.GetString("Generate.ListAvailableHeader", resourceCulture);
            }
        }
        
        internal static string Init_Error_DirectoryExists {
            get {
                return ResourceManager.GetString("Init.Error.DirectoryExists", resourceCulture);
            }
        }
        
        internal static string Init_Error_InvalidDirectoryName {
            get {
                return ResourceManager.GetString("Init.Error.InvalidDirectoryName", resourceCulture);
            }
        }
        
        internal static string Init_Choice_Language {
            get {
                return ResourceManager.GetString("Init.Choice.Language", resourceCulture);
            }
        }
        
        internal static string Init_Error_Throw {
            get {
                return ResourceManager.GetString("Init.Error.Throw", resourceCulture);
            }
        }
        
        internal static string Init_Choice_BinaryType {
            get {
                return ResourceManager.GetString("Init.Choice.BinaryType", resourceCulture);
            }
        }
        
        internal static string Run_Error_ProjectNotFound {
            get {
                return ResourceManager.GetString("Run.Error.ProjectNotFound", resourceCulture);
            }
        }
        
        internal static string Init_Error_ProjectNotExe {
            get {
                return ResourceManager.GetString("Init.Error.ProjectNotExe", resourceCulture);
            }
        }
        
        internal static string Run_Error_ExeNotFound {
            get {
                return ResourceManager.GetString("Run.Error.ExeNotFound", resourceCulture);
            }
        }
    }
}
